# Generated by Django 3.2 on 2023-10-06 08:07

import django.contrib.auth.validators
from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(
                blank=True,
                help_text='Укажите биография пользователя',
                verbose_name='биография пользователя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(
                help_text='Укажите свою электронную почту. На неё вам придёт письмо с кодом подтвержедния',
                max_length=254,
                unique=True,
                verbose_name='Электронная почта',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(
                blank=True,
                help_text='Укажите имя',
                max_length=150,
                verbose_name='Имя',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(
                blank=True,
                help_text='Укажите фамилию',
                max_length=150,
                verbose_name='Фамилия',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrator'),
                    ('moderator', 'Moderator'),
                    ('user', 'User'),
                ],
                default='user',
                help_text='Укажите роль пользователя',
                max_length=50,
                verbose_name='Роль',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(
                help_text='Укажите ваш псевдоним',
                max_length=150,
                unique=True,
                validators=[
                    reviews.validators.validate_name,
                    django.contrib.auth.validators.UnicodeUsernameValidator(),
                ],
                verbose_name='Псевдоним',
            ),
        ),
    ]
