# Generated by Django 3.2 on 2023-09-28 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230928_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(
                max_length=200, verbose_name='Код подтверждения'
            ),
        ),
    ]
