# Generated by Django 3.2 on 2023-09-28 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_myuser_confirmation_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='confirmation_code',
        ),
    ]
