# Generated by Django 3.2 on 2023-09-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0010_alter_myuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(
                max_length=254, unique=True, verbose_name='Электронная почта'
            ),
        ),
    ]
