# Generated by Django 3.2 on 2023-09-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0012_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={
                'ordering': ['id'],
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.AddConstraint(
            model_name='myuser',
            constraint=models.CheckConstraint(
                check=models.Q(_negated=True, username__iexact='me'),
                name='username_is_not_me',
            ),
        ),
    ]
