# Generated by Django 3.2 on 2023-09-29 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0015_remove_myuser_username_is_not_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['id']},
        ),
    ]
