# Generated by Django 3.2 on 2023-09-30 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0017_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(
                max_length=150,
                null=True,
                unique=True,
                verbose_name='Имя пользователя',
            ),
        ),
    ]
