# Generated by Django 3.2 on 2023-09-30 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_myuser_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='myuser',
            name='username_is_not_me',
        ),
    ]
