# Generated by Django 3.2 on 2023-09-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0021_remove_myuser_username_is_not_me'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='myuser',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(
                choices=[
                    ('admin', 'Administrator'),
                    ('moderator', 'Moderator'),
                    ('user', 'User'),
                ],
                default='user',
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
