# Generated by Django 3.2 on 2023-10-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0026_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
