# Generated by Django 3.2 on 2023-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0028_myuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
