# Generated by Django 3.2 on 2023-09-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvImport',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('csv_file', models.FileField(upload_to='static/uploads')),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='gengetitle',
            options={'verbose_name_plural': 'GengeTitle'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'verbose_name_plural': 'Reviews'},
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='test',
            new_name='text',
        ),
    ]
