# Generated by Django 3.2 on 2023-09-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reviews', '0002_auto_20230925_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvimport',
            name='csv_file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
